# Generated by Django 4.2.6 on 2023-11-13 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0003_sharedcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SharedCollection',
        ),
    ]
