# Generated by Django 4.2.6 on 2023-11-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_sharedcollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedCollection',
        ),
    ]
